server:
  port: 8080

spring:
  application:
    name: Loobby

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  flyway:
    enabled: false
  web:
    error:
      include-stacktrace: ALWAYS

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-minutes: 15
    refresh-token-validity-minutes: 10080   # 60 * 24 * 7  (1 semana)

management:
  endpoints:
    web:
      exposure:
        include: health, info

file:
  storage:
    location: ./uploads
    public-base-url: http://127.0.0.1:8080/files  # Mudar caminho quando em produção

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.jammes: DEBUG
